### PR TITLE
Use common generateName for storage

### LINKED ISSUE #358: registry fail to start (4.2-2019-08-08-070705)
Registry fails to start after nightly build on azure

```
openshift-image-registry                                cluster-image-registry-operator-c8d6678cd-v8zmp                   0/1     CrashLoopBackOff   10         33m
```

```
[mjudeiki@redhat installer]$ oc describe pod cluster-image-registry-operator-c8d6678cd-v8zmp 
Name:               cluster-image-registry-operator-c8d6678cd-v8zmp
Namespace:          openshift-image-registry
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               mjtest-2gslw-master-0/10.0.0.7
Start Time:         Thu, 08 Aug 2019 09:40:26 +0100
Labels:             name=cluster-image-registry-operator
                    pod-template-hash=c8d6678cd
Annotations:        openshift.io/scc: restricted
Status:             Running
IP:                 10.129.0.20
Controlled By:      ReplicaSet/cluster-image-registry-operator-c8d6678cd
Containers:
  cluster-image-registry-operator:
    Container ID:  cri-o://c07f5c2d6d41e4ad5e78b34f50c0081202d065e2d5ce3a5af1029ac3c518c632
    Image:         registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:1f03caa36cec488f8b8a854c81577f7e89e822623396e83cbb9275c8090643db
    Image ID:      registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:1f03caa36cec488f8b8a854c81577f7e89e822623396e83cbb9275c8090643db
    Port:          60000/TCP
    Host Port:     0/TCP
    Command:
      cluster-image-registry-operator
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 08 Aug 2019 10:11:11 +0100
      Finished:     Thu, 08 Aug 2019 10:11:30 +0100
    Ready:          False
    Restart Count:  10
    Requests:
      cpu:  10m
    Environment:
      RELEASE_VERSION:  4.2.0-0.okd-2019-08-08-070705
      WATCH_NAMESPACE:  openshift-image-registry (v1:metadata.namespace)
      OPERATOR_NAME:    cluster-image-registry-operator
      IMAGE:            registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:e252d48cc5108337c1a1b4a90366898da3454b50e4407a620d8e7ba146758e15
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-image-registry-operator-token-dc5kt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  cluster-image-registry-operator-token-dc5kt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cluster-image-registry-operator-token-dc5kt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 120s
                 node.kubernetes.io/unreachable:NoExecute for 120s
Events:
  Type     Reason     Age                    From                            Message
  ----     ------     ----                   ----                            -------
  Normal   Scheduled  34m                    default-scheduler               Successfully assigned openshift-image-registry/cluster-image-registry-operator-c8d6678cd-v8zmp to mjtest-2gslw-master-0
  Normal   Pulling    34m                    kubelet, mjtest-2gslw-master-0  Pulling image "registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:1f03caa36cec488f8b8a854c81577f7e89e822623396e83cbb9275c8090643db"
  Normal   Pulled     33m                    kubelet, mjtest-2gslw-master-0  Successfully pulled image "registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:1f03caa36cec488f8b8a854c81577f7e89e822623396e83cbb9275c8090643db"
  Normal   Created    30m (x5 over 33m)      kubelet, mjtest-2gslw-master-0  Created container cluster-image-registry-operator
  Normal   Started    30m (x5 over 33m)      kubelet, mjtest-2gslw-master-0  Started container cluster-image-registry-operator
  Normal   Pulled     28m (x5 over 33m)      kubelet, mjtest-2gslw-master-0  Container image "registry.svc.ci.openshift.org/origin/4.2-2019-08-08-070705@sha256:1f03caa36cec488f8b8a854c81577f7e89e822623396e83cbb9275c8090643db" already present on machine
  Warning  BackOff    3m54s (x110 over 33m)  kubelet, mjtest-2gslw-master-0  Back-off restarting failed container
```
Logs: 
```
[mjudeiki@redhat installer]$ oc logs -f cluster-image-registry-operator-c8d6678cd-v8zmp 
I0808 09:11:11.318896       1 main.go:20] Cluster Image Registry Operator Version: 4.0.0-300-g4a57a26-dirty
I0808 09:11:11.318989       1 main.go:21] Go Version: go1.12.5
I0808 09:11:11.318996       1 main.go:22] Go OS/Arch: linux/amd64
I0808 09:11:11.322967       1 controller.go:473] waiting for informer caches to sync
I0808 09:11:12.925302       1 controller.go:482] started events processor
I0808 09:11:13.381040       1 azure.go:144] attempt to create azure storage account mjtest2gslwmtnn4 (resourceGroup="mjtest-2gslw-rg", location="eastus")...
I0808 09:11:30.889054       1 azure.go:174] azure storage account mjtest2gslwmtnn4 has been created
E0808 09:11:30.925871       1 runtime.go:69] Observed a panic: "slice bounds out of range" (runtime error: slice bounds out of range)
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:54
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/storage/azure/azure.go:471
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/resource/generator.go:102
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/resource/generator.go:143
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:121
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:159
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:249
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:256
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 253 [running]:
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1863020, 0x3052d20)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/openshift/cluster-image-registry-operator/pkg/storage/azure.(*driver).CreateStorage(0xc000a01ec0, 0xc0005d0840, 0xc0005c2101, 0x1e66f20)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/storage/azure/azure.go:471 +0x18da
github.com/openshift/cluster-image-registry-operator/pkg/resource.(*Generator).syncStorage(0xc0000be280, 0xc0005d0840, 0x41365a, 0xc000a41580)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/resource/generator.go:102 +0xc9
github.com/openshift/cluster-image-registry-operator/pkg/resource.(*Generator).Apply(0xc0000be280, 0xc0005d0840, 0x0, 0x0)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/resource/generator.go:143 +0x4d
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).createOrUpdateResources(0xc0005c4180, 0xc0005d0840, 0x7, 0xc0000f6801)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:121 +0x1a9
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).sync(0xc0005c4180, 0x1e765b0, 0xc0000be320)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:159 +0x108e
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).eventProcessor.func1(0xc0005c4180, 0x17bbd00, 0x1dde3d0)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:249 +0x98
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).eventProcessor(0xc0005c4180)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:256 +0x45
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a41560)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a41560, 0x3b9aca00, 0x0, 0x1, 0xc0000886c0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000a41560, 0x3b9aca00, 0xc0000886c0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).Run
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:480 +0xf5e
[mjudeiki@redhat installer]$ 
```

/kind bug

### PR DESCRIPTION
**Pull request by coreydaley**
- Use a commont generateName function to generate storage name
- Wrap the swift storage creation in a loop that checks for an existing container
- Swift test fixes donated by @Fedosin, thanks!

Fixes #358

### CODE REVIEW

File: pkg/storage/util/util.go [hunk 1]
```diff
@@ -104,3 +105,43 @@ func GetValueFromSecret(sec *corev1.Secret, key string) (string, error) {
 	}
 	return "", fmt.Errorf("secret %q does not contain required key %q", fmt.Sprintf("%s/%s", sec.Namespace, sec.Name), key)
 }
+
+// GenerateStorageName generates a unique name for the storage
+// medium that the registry will use
```
Comment (ricardomaraschini) [inline pkg/storage/util/util.go]: Not sure if it should really be a concern but we could "normalize" the bucket name to contain only what  providers consider to be a valid "bucket name":

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html
https://cloud.google.com/storage/docs/naming

It would make this function more "future proof".

File: pkg/storage/util/util_test.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+func (m MockInfrastructureLister) List(selector labels.Selector) ([]*configv1.Infrastructure, error) {
+	var list []*configv1.Infrastructure
+	return list, nil
+}
+
+func TestGenerateStorageName(t *testing.T) {
+	l := regopclient.Listers{Infrastructures: MockInfrastructureLister{}}
+	tests := [][]string{
+		// test with no additionals
+		{},
```
Comment (ricardomaraschini) [inline pkg/storage/util/util_test.go]: Maybe add an extra `nil` test case here? In practice the behavior will be the same as with `{}` but it may help in the future.

File: pkg/storage/swift/swift.go [hunk 3]
```diff
@@ -348,33 +353,49 @@ func (d *driver) CreateStorage(cr *imageregistryv1.Config) error {
...
-		},
-	}
+		if err = d.containerExists(client, cr.Spec.Storage.Swift.Container); err != nil {
+			if _, ok := err.(*gophercloud.ErrResourceNotFound); ok {
+				if !generatedName {
+					util.UpdateCondition(cr, imageregistryv1.StorageExists, operatorapi.ConditionFalse, "Unable to access container", "The user provided container does not exist")
+					break
+				}
+			} else {
+				cr.Spec.Storage.Swift.Container = ""
```
Comment (ricardomaraschini) [inline pkg/storage/swift/swift.go]: Let's see if I am getting this right. If the user provides a container name and we fail to check if the container exists(by any other reason than `gophercloud.ErrResourceNotFound`) we gonna ended up creating a new one with a new name. Is that right?

Also just for my understanding, if the container does exist why do we attempt to recreate it? I would assume that if the container exists we would just say: "OK, it is created".

Comment (ricardomaraschini) [reply pkg/storage/swift/swift.go]: Maybe it is by design but I added the following "test":

```
func TestInternalServerError(t *testing.T) {                                                                                                        
        th.SetupHTTP()                                                                                                                  
        defer th.TeardownHTTP()                                                                                                         
        handleAuthentication(t, "container")                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                 
        th.Mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                fmt.Println(r.URL)                                                                                                                                                                                                    
                w.WriteHeader(500)                                                                                                                                                                                                                                               
        })                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                 
        d, installConfig := mockConfig(false, th.Endpoint()+"v3", MockUPISecretNamespaceLister{})                                                                                                                                                                                
        d.CreateStorage(&installConfig)                                                                                                 
}
```

What I noticed is that the endpoint is called 5000 times, on the first call the url is `/registry`, all other 4999 are something like `/user-j45xj-image-registry--gmwjgsapgatlmodylumguqdiwwmnppqimge`, that makes me believe that if the remote server is crashed we may have other problems.

File: pkg/storage/util/util.go (hunk 1 above)
Comment (coreydaley) [reply pkg/storage/util/util.go]: The only thing I see missing would be the ending with a dash, I will update to remove a dash at the end

File: pkg/storage/util/util_test.go (hunk 2 above)
Comment (coreydaley) [reply pkg/storage/util/util_test.go]: Good idea, added in next push

File: pkg/storage/swift/swift.go (hunk 3 above)
Comment (coreydaley) [reply pkg/storage/swift/swift.go]: It is only called the other 4,999 times if the names that we generate are taken.

**Comment by coreydaley** [comment]
@ricardomaraschini ptal, updated per your comments

File: pkg/storage/swift/swift.go (hunk 3 above)
Comment (ricardomaraschini) [reply pkg/storage/swift/swift.go]: @coreydaley So, if user provided `X` as the container name and we fail to check if `X`  exists(like the `500` error I used on my test) shall we go ahead and generate a new random name?

I am trying to understand if that is the expected behavior, strange things can happen when we have a network connection involved :-)

Comment (ricardomaraschini) [reply pkg/storage/swift/swift.go]: Ah, sorry. I commented before noting you have already changed the implementation. LGTM now.

**Comment by coreydaley** [comment]
/retest
networking flake
panic: Get https://api.ci-op-thmg1jwy-12abb.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions/version: dial tcp: i/o timeout

**Comment by coreydaley** [comment]
/retest
 Aug  9 12:58:41.119: INFO: Couldn't delete ns: "e2e-svcaccounts-6131": namespace e2e-svcaccounts-6131 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace e2e-svcaccounts-6131 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})

**Comment by bparees** [comment]
/approve

please have someone from @openshift/openshift-team-developer-experience lgtm

File: pkg/storage/util/util.go [hunk 4]
```diff
@@ -104,3 +105,48 @@ func GetValueFromSecret(sec *corev1.Secret, key string) (string, error) {
...
+	var parts []string
+
+	// Put the infrastructure name first
+	parts = append(parts, infra.Status.InfrastructureName)
+
+	// Image Registry Name second
+	parts = append(parts, imageregistryv1.ImageRegistryName)
+
+	// Additional information provided to the function third
+	parts = append(parts, additionalInfo...)
```
Comment (Fedosin) [inline pkg/storage/util/util.go]: For Swift additionalInfo is empty, so the generated name looks like "mfedosin-g7p5v-image-registry--myuprdgckxphuptgcelojvpgaphavyp" with double "-". Not sure if this was done intentionally, but I suggest to append additionalInfo to the parts only if it's not empty.

File: pkg/storage/swift/swift.go [hunk 5]
```diff
@@ -348,33 +353,61 @@ func (d *driver) CreateStorage(cr *imageregistryv1.Config) error {
...
 
-	// Generate new container name if it wasn't provided.
-	// The name has cluster ID as a prefix plus "image-registry" suffix, which is complemented
-	// by 8 capital latin letters
-	// Example of a generated name: user-298xw-image-registry-FHEIBGDD
-	if cr.Spec.Storage.Swift.Container == "" {
-		cr.Spec.Storage.Swift.Container = generateContainerName(infra.Status.InfrastructureName)
-	}
+	generatedName := false
+	for i := 0; i < 5000; i++ {
```
Comment (Fedosin) [inline pkg/storage/swift/swift.go]: Does it make sense to declare 5000 as a constant? like "const numRetries = 5000"

File: pkg/storage/util/util.go (hunk 4 above)
Comment (coreydaley) [reply pkg/storage/util/util.go]: Thanks, I didn't catch that, will fix

File: pkg/storage/swift/swift.go (hunk 5 above)
Comment (coreydaley) [reply pkg/storage/swift/swift.go]: probably

**Comment by coreydaley** [comment]
@Fedosin thanks for the review, updated per your comments

**Comment by coreydaley** [comment]
@bparees ptal

**Comment by bparees** [comment]
@coreydaley 
https://github.com/openshift/cluster-image-registry-operator/pull/355#issuecomment-520076396

**Comment by coreydaley** [comment]
@ricardomaraschini @gabemontero Can one of you ptal and let me know if you have any questions or lgtm
