### PR TITLE
skip driver.CompleteConfiguration if the driver is nil

### LINKED ISSUE #148: Operator crashes when storage backend cannot be detected
Seems #58 is back, seeing this on BYOR control plane cluster, no cloudprovider set:
```
I0111 01:01:08.021751       1 main.go:24] Cluster Image Registry Operator Version: 2e125da-dirty
I0111 01:01:08.021867       1 main.go:25] Go Version: go1.10.3
I0111 01:01:08.021872       1 main.go:26] Go OS/Arch: linux/amd64
I0111 01:01:08.049742       1 controller.go:378] waiting for informer caches to sync
I0111 01:01:09.251837       1 controller.go:387] started events processor
I0111 01:01:09.263690       1 bootstrap.go:102] generating registry custom resource
E0111 01:01:09.267640       1 storage.go:106] unknown storage backend: 
E0111 01:01:09.267778       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/bootstrap.go:128
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:122
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:213
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:220
/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:385
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12918ad]

goroutine 96 [running]:
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x144be20, 0x223d8d0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).Bootstrap(0xc42002c160, 0xc420810480, 0x1)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/bootstrap.go:128 +0x6ad
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).sync(0xc42002c160, 0x17f2570, 0xc4200c7460)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:122 +0x1e6
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).eventProcessor.func1(0xc42002c160, 0x13b60a0, 0x17bb930)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:213 +0x8f
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).eventProcessor(0xc42002c160)
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:220 +0x8e
github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).(github.com/openshift/cluster-image-registry-operator/pkg/operator.eventProcessor)-fm()
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:385 +0x2a
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420aa80a0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420aa80a0, 0x3b9aca00, 0x0, 0x9c295639fd35a501, 0xc4200b0de0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420aa80a0, 0x3b9aca00, 0xc4200b0de0)
	/go/src/github.com/openshift/cluster-image-registry-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/openshift/cluster-image-registry-operator/pkg/operator.(*Controller).Run
	/go/src/github.com/openshift/cluster-image-registry-operator/pkg/operator/controller.go:385 +0xc32
```

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes #148

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal
(looks like ci for the registry operator might be broken right now also)

**Comment by coreydaley** [comment]
alright, lets see if this commit fixes is

File: pkg/resource/generator.go [hunk 1]
```diff
@@ -104,9 +104,7 @@ func (g *Generator) syncStorage(cr *regopapi.Config, modified *bool) error {
 		return err
 	}
 
-	if len(driver.GetStorageName()) == 0 {
```
Comment (coreydaley) [inline pkg/resource/generator.go]: I'm pretty sure that this was causing syncStorage to create a new bucket after the finalizer ran

File: pkg/storage/s3/s3.go [hunk 2]
```diff
@@ -437,12 +437,22 @@ func (d *driver) RemoveStorage(cr *opapi.Config, modified *bool) error {
 		return err
 	}
 
+	// Wait until the bucket does not exist
```
Comment (coreydaley) [inline pkg/storage/s3/s3.go]: This probably isn't doing a whole lot toward fixing the issue, but I think it's worth having

File: pkg/storage/s3/s3.go [hunk 3]
```diff
@@ -437,12 +437,22 @@ func (d *driver) RemoveStorage(cr *opapi.Config, modified *bool) error {
...
+			util.UpdateCondition(cr, opapi.StorageExists, operatorapi.ConditionTrue, aerr.Code(), aerr.Error(), modified)
+		}
+
+		return err
+	}
+
 	cr.Spec.Storage.S3.Bucket = ""
 	d.Config.Bucket = ""
 	cr.Status.Storage.S3 = d.Config.DeepCopy()
-	if d.StorageChanged(cr, modified) {
```
Comment (coreydaley) [inline pkg/storage/s3/s3.go]: Pretty sure that this was keeping the cr from being updated since we removed the bucket from the Spec and the Status

File: pkg/storage/s3/s3.go [hunk 4]
```diff
@@ -437,12 +437,22 @@ func (d *driver) RemoveStorage(cr *opapi.Config, modified *bool) error {
...
-		*modified = true
-	}
+
+	*modified = true
```
Comment (bparees) [inline pkg/storage/s3/s3.go]: you still need to explicitly check if you are changing the object, otherwise you risk a hotloop:

```
if len(cr.Spec.Storage.S3.Bucket)!=0 {
 cr.Spec.Storage.S3.Bucket="" 
 *modified=true
}
```
etc

Comment (coreydaley) [reply pkg/storage/s3/s3.go]: updated in current push
